//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrgovinaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class artikal
    {
        public int idartikal { get; set; }
        public string naziv { get; set; }
        public decimal cena { get; set; }
        public string jm { get; set; }
        public decimal kolnastanju { get; set; }
    }
}
