//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrgovinaMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class artikal
    {
        public int idartikal { get; set; }

        [Required(ErrorMessage = "Morate uneti naziv artikla!")]
        public string naziv { get; set; }

        [Required(ErrorMessage = "Morate uneti cenu!")]
        [Range(0, 9999999999, ErrorMessage = "Cena mora biti izmedju 0 i 9.999.999.999 din!")]
        public decimal cena { get; set; }

        [Required(ErrorMessage = "Morate uneti jedinicu mere!")]
        public string jm { get; set; }

        [Required(ErrorMessage = "Morate uneti trenutnu količinu na stanju!")]
        [Range(0, 9999999999, ErrorMessage = "Količina mora biti izmedju 0 i 9.999.999.999!")]
        public decimal kolnastanju { get; set; }
    }
}
