//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrgovinaMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSTREntities : DbContext
    {
        public dbSTREntities()
            : base("name=dbSTREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<artikal> artikals { get; set; }
        public virtual DbSet<kupac> kupacs { get; set; }
        public virtual DbSet<racun> racuns { get; set; }
        public virtual DbSet<stavkaracuna> stavkaracunas { get; set; }
    }
}
