//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrgovinaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kupac
    {
        public string pib { get; set; }
        public string naziv { get; set; }
        public string adresa { get; set; }
        public string brtel { get; set; }
        public int idkupac { get; set; }
    }
}
